### PR TITLE
Testing pull request trigger

### PR DESCRIPTION
**Pull request by thomashenson**

### CODE REVIEW

**Comment by Jordancooke** [comment]
Code looks good, I noticed that there are a few nested loops which if possible would be nice to have removed as I can imagine it adds some extra time complexity, but this is all down to if you think this will become a possible problem, due to things like increasing data sizes.

aws-test.sh and install-dependencies.sh can be removed as they are either obsolete or accessed though another repo.

“steps” needs to be added under the parallel step in the pipeline.yml, so that it can be truly parallel.

Inside the method at line 64 + 66, the line length isn’t optional sadly, can you adjust to be within the line limit without using cheat codes please.

Serverless.yml might need to consider moving sqs_queue_url and sns_topic_arn into secrets or passed it in, as I’m unsure if this is classified as sensitive or not. Might be best to confirm with Ian.

When it comes to the tests, I noticed that you have placed them all inside the same test file and separated them out with banners. If possible could you split both the wrangler test and methods tests into different test files to help with readability and make it easier to deal with changes.

Once you have made these changes let me know and I will approve the merge 😃

**Comment by thomashenson** [comment]
- > Code looks good, I noticed that there are a few nested loops which if possible would be nice to have removed as I can imagine it adds some extra time complexity, but this is all down to if you think this will become a possible problem, due to things like increasing data sizes.

As discussed with @Jordancooke & @KrisRogos this is essential for the way in which the data is presented to us. Current runtime is around 2 seconds, if it increases substantially, will be something to consider.
- > aws-test.sh and install-dependencies.sh can be removed as they are either obsolete or accessed though another repo.

Files have now been removed.
- > “steps” needs to be added under the parallel step in the pipeline.yml, so that it can be truly parallel.

This has now been added to the pipeline.
- > Inside the method at line 64 + 66, the line length isn’t optional sadly, can you adjust to be within the line limit without using cheat codes please.

Tested this concept but could not get this to work on line 64 and satisfy the needs of flake8 at the same time. Was also much less readable. So a #noqa remains on line 64. Line 66 has been adjusted to multi-line.
- > Serverless.yml might need to consider moving sqs_queue_url and sns_topic_arn into secrets or passed it in, as I’m unsure if this is classified as sensitive or not. Might be best to confirm with Ian.

In progress.
- > When it comes to the tests, I noticed that you have placed them all inside the same test file and separated them out with banners. If possible could you split both the wrangler test and methods tests into different test files to help with readability and make it easier to deal with changes.

After having a few issues with the tests (preventing the code from running on AWS) this issue has now been resolved. Tests have been moved into seperate files for both wrangler and method.

**Comment by Jordancooke** [comment]
Great stuff, happy for this to be merged.

**Comment by Piwington** [comment]
Forgot to mention. I also ran a quick coverage report which seemed to suggest that in conftest.py certain lines weren't running. As this is in the test folder I'm surprised this is the case and you may wish to check it out?
def sqs(aws_credentials):
def lambda_mock(aws_credentials):

**Pull request merged**
